apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatelegram.fullname" . }}
  labels:
    {{- include "chatelegram.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "chatelegram.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chatelegram.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chatelegram.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 7001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /alive
              port: metrics
          readinessProbe:
            httpGet:
              path: /ready
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: OPENAI_API_KEY
              value: {{ .Values.image.openai_token }}
            - name: TELEGRAM_BOT_TOKEN
              value: {{ .Values.image.telegram_bot_token }}
            - name: GPT_MAX_TOKEN
              value: {{ .Values.image.gpt_max_token | quote }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
